### ISSUE TITLE
Remove requirement for unused configurations

### ISSUE THREAD

**Issue by olivierdupuis** [LewisCharlesBaker/droughty#13]
As a user of droughty, I want to remove unused configurations from my `droughty_project.yml` file, so that I can keep that file as simple and clean as possible.

For example, if I'm not to use the lookml command, I would like to be able to remove the following configs: 

```
explores:
  parent_table: 
    - actors_dim
  dimensions: 
    - events_fct
  facts:
    - narratives_fct
 ```
