### ISSUE TITLE
Add Looker refinement-type functionality to test generation

### ISSUE THREAD

**Issue by Terroface** [LewisCharlesBaker/droughty#36]
When `fks` are generated `null_safe` it causes `non_null` errors on  the automatically generated tests.

<img width="840" alt="image" src="https://user-images.githubusercontent.com/38318312/194915253-b4bb2e38-659f-48d7-855e-321832263237.png">

In order to allow for this, it would be great to be able to define in `droughty_project` which columns to ignore creating certain tests for. Syntax could be something like this:

```yml
ignore_tests:
  - not_null:
    - model: wh_operations__events_fact
    - columns:
      - document_fk
      - case_fk
    - model: wh_operations__cases_fact
    - columns:
      - employee_case_owner_fk

```
